// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using moti_lab1_core2.Models;
using System;

namespace moti_lab1_core2.Migrations
{
    [DbContext(typeof(LabContext))]
    [Migration("20170929103442_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("moti_lab1_core2.Models.Alternative", b =>
                {
                    b.Property<int>("ANum")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AName");

                    b.HasKey("ANum");

                    b.ToTable("Alternatives");
                });

            modelBuilder.Entity("moti_lab1_core2.Models.Criterion", b =>
                {
                    b.Property<int>("CNum")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CName");

                    b.Property<int>("CRange");

                    b.Property<string>("CType");

                    b.Property<int>("CWeight");

                    b.Property<string>("Edizmer");

                    b.Property<string>("OptimType");

                    b.Property<string>("ScaleType");

                    b.HasKey("CNum");

                    b.ToTable("Criterions");
                });

            modelBuilder.Entity("moti_lab1_core2.Models.LPR", b =>
                {
                    b.Property<int>("LNum")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LName");

                    b.Property<int>("LRange");

                    b.HasKey("LNum");

                    b.ToTable("LPRs");
                });

            modelBuilder.Entity("moti_lab1_core2.Models.Mark", b =>
                {
                    b.Property<int>("MNum")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CNum");

                    b.Property<string>("MNAme");

                    b.Property<int>("MRange");

                    b.Property<int>("NormMark");

                    b.Property<int>("NumMark");

                    b.HasKey("MNum");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("moti_lab1_core2.Models.Result", b =>
                {
                    b.Property<int>("RNum")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ANum");

                    b.Property<int>("AWeight");

                    b.Property<int>("LNum");

                    b.Property<int>("Range");

                    b.HasKey("RNum");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("moti_lab1_core2.Models.Vector", b =>
                {
                    b.Property<int>("VNum")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Anum");

                    b.Property<int>("MNum");

                    b.HasKey("VNum");

                    b.ToTable("Vectors");
                });
#pragma warning restore 612, 618
        }
    }
}
